apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: {{ project_name | replace: "_", "-" }}
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/{{ github_org }}/{{ github_repo }}.git
  ref:
    branch: {{ default_branch }}
  secretRef:
    name: github-deploy-key
