apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

components:
  {% if feature_flagger %}
  - ../../components/flagger
  {% endif %}

patches:
  - target:
      kind: HelmRelease
      name: {{ project_name | replace: "_", "-" }}
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: {{ project_name | replace: "_", "-" }}
      spec:
        values:
          services:
            "":
              scaling:
                minScale: {% if use_default_scaling %}2{% else %}{{ prod_min_scale }}{% endif %}
                maxScale: {% if use_default_scaling %}20{% else %}{{ prod_max_scale }}{% endif %}
              resources:
                requests:
                  cpu: "{% if use_default_scaling %}250m{% else %}{{ prod_cpu_request }}{% endif %}"
                  memory: "{% if use_default_scaling %}256Mi{% else %}{{ prod_memory_request }}{% endif %}"
                limits:
                  cpu: "{% if use_default_scaling %}1000m{% else %}{{ prod_cpu_limit }}{% endif %}"
                  memory: "{% if use_default_scaling %}512Mi{% else %}{{ prod_memory_limit }}{% endif %}"
          {% if feature_postgres %}
          postgres:
            instances: 3
            parameters:
              synchronous_commit: "remote_apply"
              shared_buffers: "2Gi"
              max_connections: "300"
            resources:
              requests:
                cpu: "1"
                memory: "2Gi"
              limits:
                cpu: "2"
                memory: "4Gi"
            storage:
              size: "200Gi"
            backup:
              objectStore:
                destinationPath: "s3://{{ project_name | replace: '_', '-' }}-postgres-backups/prod/"
                data:
                  compression: zstd
                  jobs: 4
                wal:
                  compression: zstd
                  maxParallel: 8
              retentionPolicy: "{{ backup_retention_prod }}d"
          {% endif %}
          {% if event_source_kafka %}
          kafka:
            sources:
              {{ kafka_topic }}:
                bootstrapServers:
                  - "{{ kafka_bootstrap_servers_prod }}"
                consumers: 10
                initialOffset: latest
                delivery:
                  retry: 10
                  backoffDelay: "PT2S"
          {% endif %}

 {% if feature_s3 %}
configMapGenerator:
  - name: s3-config
    behavior: create
    literals:
      - S3_ENDPOINT=https://s3.amazonaws.com
      - S3_BUCKET=data-prod
      - S3_REGION=us-east-1
 {% endif %}
