apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../base

commonLabels:
  environment: development

patches:
  - target:
      kind: Service
      name: rust-service
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1min-scale
        value: "0"
      - op: add
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1max-scale
        value: "3"
