{% if event_source_kafka %}
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: {{ project_name | replace: "_", "-" }}-kafka-source
  namespace: {{ target_namespace }}
spec:
  bootstrapServers:
  - {{ kafka_bootstrap_servers_staging }}
  consumers: 5
  initialOffset: earliest
{% endif %}
