apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - kafka-source.yaml
  - dlq-handler.yaml

labels:
  - pairs:
      component: kafka
      app.kubernetes.io/part-of: {{ project_name | replace: "_", "-" }}
    includeSelectors: false
