apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - postgres-objectstore.yaml
  - postgres-cluster.yaml
  - postgres-backup.yaml
  - postgres-pooler.yaml
  - postgres-podmonitor.yaml
  - postgres-alerts.yaml

labels:
  - pairs:
      component: postgres
      app.kubernetes.io/part-of: {{ project_name | replace: "_", "-" }}
    includeSelectors: false
