apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - knative-service.yaml

images:
  - name: ghcr.io/test-org/test-app
    newName: localhost:5001/test-app-no-s3
    newTag: local-local-1767812982-035a9e6

namespace: default
